<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 7.1.1 (Python 3.13.0 on linux)" generated="2024-11-29T18:53:42.782384" rpa="false" schemaversion="5">
<suite id="s1" name="testDemo1" source="/robot_selenium-tests/testDemo1.robot">
<test id="s1-t1" name="Validate UnSuccessful Login" line="13">
<kw name="Open Page">
<msg time="2024-11-29T18:53:42.820626" level="FAIL">No keyword with name 'Open Page' found.</msg>
<arg>https://rahulshettyacademy.com/</arg>
<arg>${browser_name}</arg>
<status status="FAIL" start="2024-11-29T18:53:42.820592" elapsed="0.000078">No keyword with name 'Open Page' found.</status>
</kw>
<status status="FAIL" start="2024-11-29T18:53:42.819354" elapsed="0.001510">No keyword with name 'Open Page' found.</status>
</test>
<doc>To Validate the Login form</doc>
<status status="FAIL" start="2024-11-29T18:53:42.785394" elapsed="0.035750"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="1" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" skip="0" id="s1" name="testDemo1">testDemo1</stat>
</suite>
</statistics>
<errors>
<msg time="2024-11-29T18:53:42.816367" level="ERROR">Error in file '/robot_selenium-tests/testDemo1.robot' on line 3: Importing library 'SeleniumLibrary' failed: ModuleNotFoundError: No module named 'SeleniumLibrary'
Traceback (most recent call last):
  None
PYTHONPATH:
  /usr/local/bin
  /usr/local/lib/python313.zip
  /usr/local/lib/python3.13
  /usr/local/lib/python3.13/lib-dynload
  /usr/local/lib/python3.13/site-packages</msg>
<msg time="2024-11-29T18:53:42.817597" level="ERROR">Error in file '/robot_selenium-tests/testDemo1.robot' on line 4: Library '../customLibraries/OpenBrowser.py' does not exist.</msg>
<msg time="2024-11-29T18:53:42.818752" level="ERROR">Error in file '/robot_selenium-tests/testDemo1.robot' on line 5: Resource file '../PO/Generic.robot' does not exist.</msg>
</errors>
</robot>
